crypto/apps/hamming_code/urls.py
from django.urls import path

from . import views

app_name = 'hamming'
urlpatterns = [
    path('encode/', views.encode, name='encode'),
    path('decode/', views.decode, name='decode'),
]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('hamming-code/', include('crypto.apps.hamming_code.urls')),
    path('luhn-algorithm/', include('crypto.apps.luhn_algorithm.urls')),
    path('password-cracking/', include('crypto.apps.password_cracking.urls')),
    path('blog/', include('crypto.apps.blog.urls')),
    path('chat/', include('crypto.apps.chat.urls')),
]

crypto/apps/hamming_code/views.py
from django.template.response import SimpleTemplateResponse

from . import services as service


def encode(request):
    sequence = request.POST['sequence'][::-1]

    if len(sequence) < 4:
        return SimpleTemplateResponse(
            'hamming_code/error.html', {'error': 'The binary sequence must have length greater than or equal to 4'})

    context = {
        'even': service.encode(sequence, True)[::-1],
        'odd': service.encode(sequence, False)[::-1],
    }

    return SimpleTemplateResponse('hamming_code/encoded.html', context)


def decode(request):
    sequence = request.POST['sequence'][::-1]
    is_even = request.POST['check'] == 'even'

    if len(sequence) < 7:
        return SimpleTemplateResponse(
            'hamming_code/error.html', {'error': 'The binary sequence must have length greater than or equal to 7'})

    correct, error_position = service.detect_error(sequence, is_even)
    data = service.decode(correct)

    context = {
        'has_error': error_position != 0,
        'error_position': error_position,
        'error_bit_label': service.bit_label(error_position),
        'original': sequence[::-1],
        'corrected': correct[::-1],
        'data': data[::-1],
    }

    return SimpleTemplateResponse('hamming_code/decoded.html', context)

crypto/apps/hamming_code/templates/hamming/decoded.html
<hr>
{% if has_error %}
    There was an error in the <b class="text-uppercase">{{ error_bit_label }}</b> of the sequence.
    <br>
    {% for bit in original %}
        {% if forloop.revcounter == error_position %}
            <b class="text-danger">{{ bit }}</b>
        {% else %}
            {{ bit }}
        {% endif %}
    {% endfor %}
    <i class="fas fa-times ml-1"></i>
    <br>
    {% for bit in corrected %}
        {% if forloop.revcounter == error_position %}
            <b class="text-success">{{ bit }}</b>
        {% else %}
            {{ bit }}
        {% endif %}
    {% endfor %}
    <i class="fas fa-check ml-1"></i>
    <br>
    <br>
    The following is the corrected hamming sequence.
    {% include 'hamming/sequence-tile.html' with sequence=corrected %}
    Which can be decoded into the data bits below
{% endif %}
{% include 'hamming/sequence-tile.html' with sequence=data %}

crypto/apps/hamming_code/templates/hamming/logic.html
<div class="card shadow-sm">
    <div class="card-body">
        <ul class="nav nav-tabs" id="hammingTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="encoding-tab" data-bs-toggle="tab" data-bs-target="#encoding"
                        type="button"
                        role="tab" aria-controls="home" aria-selected="true">Encode
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="decoding-tab" data-bs-toggle="tab" data-bs-target="#decoding" type="button"
                        role="tab" aria-controls="profile" aria-selected="false">Decode
                </button>
            </li>
        </ul>
        <div class="tab-content" id="hammingTabContent">
            <div class="tab-pane fade show active" id="encoding" role="tabpanel" aria-labelledby="encode-tab">
                <form action="{% url 'hamming:encode' %}" data-partial="encodeResult"
                      data-partial-error="encodeError"
                      method="post" class="mt-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="decodeSequenceInput" class="form-label" hidden>Sequence</label>
                        <input aria-describedby="encode" class="form-control" name="sequence"
                               id="decodeSequenceInput"
                               placeholder="0000"
                               type="text" minlength="4" pattern="[01]+" data-block-pattern required>
                    </div>
                    <button type="submit" class="btn btn-secondary btn-sm">Submit</button>
                </form>

                {# Error #}
                <div id="encodeError" hidden>
                    <hr>
                    <div class='text-danger'>Uh oh. Something went wrong.</div>
                </div>

                {# Result #}
                <div id="encodeResult"></div>
            </div>
            <div class="tab-pane fade" id="decoding" role="tabpanel" aria-labelledby="decode-tab">
                <form action="{% url 'hamming:decode' %}" method="post" data-partial="decodeResult"
                      data-partial-error="decodeError" class="mt-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="decodeSequenceInput" class="form-label" hidden>Sequence</label>
                        <input aria-describedby="decode" class="form-control" name="sequence" id="decodeSequenceInput"
                               placeholder="000000"
                               type="text" minlength="7" pattern="[01]+" data-block-pattern required>
                    </div>
                    <div class="mb-3">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="check" id="evenCheckRadio" value="even"
                                   checked>
                            <label class="form-check-label" for="evenCheckRadio">Even</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="check" id="oddCheckRadio" value="odd">
                            <label class="form-check-label" for="oddCheckRadio">Odd</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>

                {# Error #}
                <div id="decodeError" hidden>
                    <hr>
                    <div class='text-danger'>Uh oh. Something went wrong.</div>
                </div>

                {# Result #}
                <div id="decodeResult"></div>

            </div>
        </div>
    </div>
</div>