crypto/apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('<str:date>/<str:name>', views.posts, name='posts'),
]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('hamming-code/', include('crypto.apps.hamming_code.urls')),
    path('luhn-algorithm/', include('crypto.apps.luhn_algorithm.urls')),
    path('password-cracking/', include('crypto.apps.password_cracking.urls')),
    path('blog/', include('crypto.apps.blog.urls')),
    path('chat/', include('crypto.apps.chat.urls')),
]

templates/about.html
{% extends 'base/main.html' %}

{% block head %}
    <title>Crypto | About</title>
    <meta name="description"
          content="This is a collaboratory work designed between Mensch272, CodeMachine0101, and Maadh.">
    {% block css %}{% endblock %}
{% endblock %}

{% block main %}
    <article>
        <header class="blog-post-header mb-3">
            <h1 class="mb-1"><strong>About</strong></h1>
        </header>

        <p>
            This site is the result of a cryptography project with the aim of creating an app or website with a
            few working cryptography exercises to improve our overall understanding of the concept.
        </p>
        <p>
            As of now the site includes the option to Verify credit card numbers, Hamming Code correction, Brute
            Force password cracking and Text Encryption
        </p>

        <h5 class="my-3">Contributors</h5>

        {% for contrib in contributors %}
            <div class="card shadow-sm mb-3">
                <div class="card-body row align-items-stretch gap-1 gap-md-3 p-4">
                    <div class="col-12 col-md-3 mb-3 mb-md-0 d-flex align-items-center justify-content-center">
                        <img src="{{ contrib.thumbnail }}" alt="{{ contrib.name }} profile image"
                             class="img-fluid rounded-circle shadow-sm">
                    </div>
                    <div class="col d-flex flex-column justify-content-center">
                        <h5 class="card-title">{{ contrib.name }}</h5>
                        <div class="meta mb-3">
                            <a href="{{ contrib.profile }}" class="text-link">{{ contrib.alias }}</a>
                            • {{ contrib.id }}
                        </div>
                        {% if contrib.description %}
                            <p>{{ contrib.description }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </article>
{% endblock %}

templates/home.html
{% extends 'base/base.html' %}
{% load static %}


{% block head %}
    <title>Cryptick | Home</title>
    <meta name="description" content="This is a group of closely related cryptography projects. [UFCFT4-15-3]">
{% endblock %}

{% block body %}
    {% include 'base/header.html' %}

    <div class="main-wrapper">

        <section class="cta-section theme-bg-light py-5">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-12 col-md-6">
                        <h1 class="heading">Cryptick</h1>
                        <p>Cryptography is the study of secure communications techniques that allow only the sender and
                            intended recipient of a message to view its contents. The term is derived from the Greek
                            word kryptos, which means hidden. It is closely associated to encryption, which is the act
                            of scrambling ordinary text into what's known as ciphertext and then back again upon
                            arrival.</p>
                        <p>This is a group of closely related projects used to explore some aspects of cryptography.</p>
                        <p><code>[UFCFT4-15-3]</code></p>
                    </div>
                    <div class="col-12 col-sm-10 col-md-6 mx-auto mx-md-0">
                        <img src="{% static '/assets/illustrations/safe.svg' %}" alt="Cover image" class="img-fluid">
                    </div>
                </div>
            </div>
        </section>

        <section class="blog-list px-3 py-5 p-md-5">
            <div class="container single-col-max-width">
                {% for post in posts %}
                    <div class="item mb-5">
                        <div class="row g-3 g-xl-0">
                            <div class="col">
                                <h3 class="title mb-1">
                                    <a class="text-link"
                                       href="{% url 'blog:posts' date=post.published name=post.link %}">
                                        {{ post.title }}
                                    </a>
                                </h3>
                                <div class="meta mb-1"><span class="date">Published on {{ post.published }}</span></div>
                                <div class="intro">{{ post.description }}</div>
                                <a class="text-link" href="{% url 'blog:posts' date=post.published name=post.link %}">Read
                                    more &rarr;</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>

        {% include 'base/footer.html' %}
    </div>
{% endblock %}