crypto/apps/luhn_algorithm/urls.py
from django.urls import path

from . import views

app_name = 'luhn_algorithm'
urlpatterns = [
    path('check/', views.check, name='check'),
    path('generate/', views.generate, name='generate'),
]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('hamming-code/', include('crypto.apps.hamming_code.urls')),
    path('luhn-algorithm/', include('crypto.apps.luhn_algorithm.urls')),
    path('password-cracking/', include('crypto.apps.password_cracking.urls')),
    path('blog/', include('crypto.apps.blog.urls')),
    path('chat/', include('crypto.apps.chat.urls')),
]

crypto/apps/luhn_algorithm/models.py
from django.db import models


class CreditCard(models.Model):
    name = models.CharField(max_length=32)
    thumbnail_link = models.CharField(max_length=64)


class CreditCardIssuer:
    amex = 1
    master_card = 2
    visa = 3
    discover = 4
    electron = 5
    maestro = 6
    dankort = 7
    interpayment = 8
    unionpay = 9
    diners = 10
    jcb = 11

    values = list(range(1, 12))

crypto/apps/luhn_algorithm/forms.py
import re

from django import forms
from django.core import validators


class CCGenerateForm(forms.Form):
    issuer = forms.ChoiceField()


class CCValidateForm(forms.Form):
    number_regex = re.compile(r'^[0-9]+$')
    card_number = forms.CharField(
        min_length=12, max_length=20,
        validators=[validators.RegexValidator(number_regex, message='Credit card number contains illegal characters.')]
    )

crypto/apps/luhn_algorithm/views.py
from urllib.parse import quote

from django.shortcuts import render
from django.template.response import SimpleTemplateResponse
from django.templatetags.static import static

from .forms import CCGenerateForm, CCValidateForm
from .models import CreditCard
from .service import validate_credit_card, CreditCardService


def check(request):
    form = CCValidateForm(request.POST, request.FILES)

    if form.is_valid():
        sequence = form.cleaned_data.get('card_number')

        pk = CreditCardService.identify_type(sequence)
        if pk is None:
            card = CreditCard(name='unknown', thumbnail_link='assets/credit_cards/unknown.png')
        else:
            card = CreditCard.objects.get(pk=pk)

        personal, checksum = CreditCardService.user_identifier(sequence)

        context = {
            'valid': validate_credit_card(sequence),
            'card_number': sequence,
            'card_system': CreditCardService.identify_system(sequence),
            'card_type': card.name,
            'card_thumbnail': static(
                card.thumbnail_link) if card.thumbnail_link else f'https://via.placeholder.com/202x122?text={quote(card.name)}',
            'card_personal': personal,
            'card_checksum': checksum,
        }

        return SimpleTemplateResponse('luhn_algorithm/check_result.html', context)
    else:
        return SimpleTemplateResponse('luhn_algorithm/error.html', {'error': form.errors['card_number'][0]})


def generate(request):
    issuer = int(request.POST['issuer'])

    try:
        card = CreditCard.objects.get(pk=issuer)
    except CreditCard.DoesNotExist:
        return SimpleTemplateResponse('luhn_algorithm/generate_error.html', {'msg': 'Credit card issuer not found.'})

    context = {
        'card_number': CreditCardService.generate_card_number(issuer),
        'card_type': card.name,
        'card_thumbnail': static(
            card.thumbnail_link) if card.thumbnail_link else f'https://via.placeholder.com/202x122?text={quote(card.name)}',
    }

    return SimpleTemplateResponse('luhn_algorithm/generate_result.html', context)


def luhn(request, context):
    gform = CCGenerateForm()
    gform.fields['issuer'].choices = [(card.pk, card.name) for card in CreditCard.objects.all()]

    context = {
        **context,
        'gform': gform,
        'vform': CCValidateForm(),
    }

    return render(request, 'posts/2021-07-12/luhn_algorithm.html', context)

crypto/apps/luhn_algorithm/templates/luhn_algorithm/check_result.html
<hr>
<div class="alert alert-{{ valid|yesno:'success,danger' }}">
    {{ valid|yesno:'Valid,Invalid' }}
</div>
<div class="row">
    <div class="col col-12 col-md-6 d-flex justify-content-center align-items-center">
        <img src="{{ card_thumbnail }}" alt="Credit Card" class="img-fluid rounded mx-auto">
    </div>
    <div class="col col-12 col-md-6">

        {# Valid #}
        <p>
            <span class="fw-bold">Luhn check</span>:
            <span class="text-{{ valid|yesno:'success,danger' }}">{{ valid|yesno:'Pass,Fail' }}</span>
        </p>

        {# System #}
        <p>
            <span class="fw-bold">Industry</span>: {{ card_system|default_if_none:'Unknown' }}
        </p>

        {# Issuer #}
        <p>
            <span class="fw-bold">Issuer</span>: {{ card_type|default_if_none:'Unknown' }}
        </p>

        {# Personal #}
        <p>
            <span class="fw-bold">Personal</span>: {{ card_personal|default_if_none:'Unknown' }}
        </p>
        <p>
            <span class="fw-bold">Checksum</span>: {{ card_checksum|default_if_none:'Unknown' }}
        </p>
    </div>
</div>

crypto/apps/luhn_algorithm/templates/luhn_algorithm/error.html
<hr>
<div class="alert alert-danger">{{ error }}</div>

crypto/apps/luhn_algorithm/templates/luhn_algorithm/generate_error.html
<hr>
{{ msg }}

crypto/apps/luhn_algorithm/templates/luhn_algorithm/generate_result.html
<hr>
<div>
    <div class="d-flex flex-column justify-content-center align-items-center">
        <img src="{{ card_thumbnail }}" alt="Credit Card" class="img-fluid rounded mx-auto">
        <span class="small text-muted">{{ card_type }}</span>
    </div>
    <div class="w-100 d-flex justify-content-center align-items-center gap-1">
        <span class="h5 m-0">{{ card_number }}</span>
        <button type="button" class="btn btn-link" onclick="navigator.clipboard.writeText('{{ card_number }}')">
            <i class="bx bx-copy"></i>
        </button>
    </div>
</div>

crypto/apps/luhn_algorithm/templates/luhn_algorithm/logic.html
{% load widget_tweaks %}
<div class="card shadow-sm">
    <div class="card-body">
        <ul class="nav nav-tabs" id="luhnTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="generate-tab" data-bs-toggle="tab" data-bs-target="#generate"
                        type="button"
                        role="tab" aria-controls="generate" aria-selected="true">Generate
                </button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="validate-tab" data-bs-toggle="tab" data-bs-target="#validate" type="button"
                        role="tab" aria-controls="validate" aria-selected="false">Validate
                </button>
            </li>
        </ul>

        <div class="tab-content" id="luhnTabContent">
            <div class="tab-pane fade show active" id="generate" role="tabpanel" aria-labelledby="generate-tab">
                {# Generate form #}
                <form action="{% url 'luhn_algorithm:generate' %}" method="post" data-partial="generate-result"
                      data-partial-error="generate-error" class="mt-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ gform.issuer.id_for_label }}" class="form-label">Issuing Network</label>
                        {% render_field gform.issuer class='form-select' %}
                    </div>
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>

                {# Generate Error #}
                <div id="generate-error" hidden>
                    <div class="card-header py-3 bg-danger">
                        <h6 class="m-0 font-weight-bold text-white">Error</h6>
                    </div>
                    <div class="card-body">
                        Uh oh. Something went wrong. Please try again.
                    </div>
                </div>

                {# Generate Result #}
                <div id="generate-result"></div>
            </div>
            <div class="tab-pane fade" id="validate" role="tabpanel" aria-labelledby="validate-tab">
                <!-- Validate Card -->
                <form action="{% url 'luhn_algorithm:check' %}" method="post"
                      data-partial="validity-check-wrapper" class="mt-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ vform.card_number.id_for_label }}" class="form-label">Credit Card Number</label>
                        {% render_field vform.card_number class='form-control' data-block-pattern=True pattern="\d+" %}
                    </div>
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>

                {# Validity Error #}
                <div id="validity-check-error" hidden>
                    <div class="card-header py-3 bg-danger">
                        <h6 class="m-0 font-weight-bold text-white">Error</h6>
                    </div>
                    <div class="card-body">
                        Uh oh. Something went wrong. Please try again.
                    </div>
                </div>

                {# Validity Result #}
                <div id="validity-check-wrapper"></div>
            </div>
        </div>
    </div>
</div>