crypto/apps/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('hamming-code/', include('crypto.apps.hamming_code.urls')),
    path('luhn-algorithm/', include('crypto.apps.luhn_algorithm.urls')),
    path('password-cracking/', include('crypto.apps.password_cracking.urls')),
    path('blog/', include('crypto.apps.blog.urls')),
    path('chat/', include('crypto.apps.chat.urls')),
]

templates/posts/2021-08-21/hiding_in_strings.html
{% extends 'base/post.html' %}
{% load widget_tweaks %}
{% load static %}

{% block article %}
    <p>Steganography is described as the art of concealing a message in another. In this case, a string
        is hidden within another string. Any innocent bystander will see the unconcealed string would
        not
        take notice to the concealed message.</p>
    <p>In cryptography, the observer is able clearly see that a message has been encrypted and this
        gives raise to scrutiny. Whereas in steganography, the intended secret message is hidden from
        outside observers, thus does not attract any unwanted attention.</p>
    <p>However, the problem with steganography is that should anyone realize the presence of a secret
        message they are able to access it easily. Hence, to truly secure the message and hide it from
        observers we must apply both.</p>

    <h5 class="my-3">Encrypting the secret message</h5>
    <p>The secret message is encrypted using a password of your choice.</p>
    <p>The password is used to seed the pseudo-random number generator. We obtain the key-stream
        by continuously generating 32-bit integers and appending their bitstring to it until we have a
        sufficient length. The binary representation of the secret message is encrypted by using the XOR
        operation with the key-stream.</p>
    <p>To decrypt the secret message, the receiver can perform the same XOR operation on their matching
        key-stream generated using
        the password.</p>
    <p>
        Pseudo-Random Number Generator (PRNG) by
        <a href="https://github.com/davidbau/seedrandom">davidbau/seedrandom</a>
    </p>

    <h5 class="my-3">Hiding the secret message in a plain string</h5>
    <p>Zero-Width Characters also known as Invisible characters are non-printing characters in the
        unicode table. As the name indicates they arent drawn in text.</p>
    <p>The below table shows the unicode characters that we will be using.</p>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Bits</th>
            <th scope="col">Char</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>00</td>
            <td>200C (A)</td>
        </tr>
        <tr>
            <td>01</td>
            <td>200D (B)</td>
        </tr>
        <tr>
            <td>10</td>
            <td>2060 (C)</td>
        </tr>
        <tr>
            <td>11</td>
            <td>2062 (D)</td>
        </tr>
        </tbody>
    </table>
    <p>The encoded bitstring is converted to invisible characters by applying the above table.</p>
    <p><b>For example:</b></p>
    <p>When <code>01101000 01101001</code> is encoded with the above table gives it gives <code>BCCABCCB</code> as a
        result</p>
    <p>There are two possible positions for the invisible characters:</p>
    <ul>
        <li>In the far side of the first space</li>
        <li>If the secret message has no space, between the first and second characters</li>
    </ul>
    <pre>Unconcealed <small class="text-muted">BCCABCCB</small>String</pre>
    <p>The resulting string is sent as the message where the receiver with the key will decrypt and
        read it.</p>

    <h5 class="my-3">Limitations</h5>
    <p>The program currently includes some limitations.</p>
    <ul>
        <li>The program is only tested to work with ascii characters that take a single byte.</li>
        <li>The secret message only supports upto 4096 characters (due to fixed keystream length).</li>
    </ul>

    <h5 class="my-3">Why implement in frontend?</h5>
    <p>This encoding technique is fully implemented in the frontend for the very simple reason of not having to
    pass the stream cipher secret key between the client and the server.</p>

    <h5 class="my-3">Test</h5>

    <div class="card shadow-sm">
        <div class="card-body">
            <ul class="nav nav-tabs" id="hideTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="string-hide-tab" data-bs-toggle="tab"
                            data-bs-target="#string-hide"
                            type="button"
                            role="tab" aria-controls="string-hide" aria-selected="true">Hide
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="string-show-tab" data-bs-toggle="tab" data-bs-target="#string-show"
                            type="button"
                            role="tab" aria-controls="string-show" aria-selected="false">Show
                    </button>
                </li>
            </ul>

            <div class="tab-content" id="hideTabContent">
                <div class="tab-pane fade show active" id="string-hide" role="tabpanel"
                     aria-labelledby="string-hide-tab"
                     x-data="alpineHideData()">
                    <form action="" class="mt-3" @submit.stop.prevent="submit()">
                        <div class="mb-3">
                            <label for="hide-message" class="form-label">Message</label>
                            <input type="text" id="hide-message" class="form-control" x-model="content.message">
                        </div>
                        <div class="mb-3">
                            <label for="hide-key" class="form-label">Key</label>
                            <input type="text" id="hide-key" class="form-control" x-model="content.key">
                        </div>
                        <div class="mb-3">
                            <label for="hide-secret-message" class="form-label">Secret Message</label>
                            <input type="text" id="hide-secret-message" class="form-control" x-model="content.secret">
                        </div>
                        <button type="submit" class="btn btn-primary">Hide</button>
                    </form>

                    <template x-if="error != null">
                        <div id="hide-error" :class="error == null ? '' : 'd-block'">
                            <hr>
                            <div class="alert alert-danger" x-text="error"></div>
                        </div>
                    </template>

                    <template x-if="result != null && error == null">
                        <div id="hide-result">
                            <hr>
                            <div class="d-flex justify-content-between align-items-center gap-2">
                                <span x-text="result"></span>
                                <button class="btn btn-link" @click.prevent="clip(result)">
                                    <i class="fas fa-copy"></i>
                                </button>
                            </div>
                        </div>
                    </template>
                </div>
                <div class="tab-pane fade" id="string-show" role="tabpanel" aria-labelledby="string-show-tab"
                     x-data="alpineShowData()">
                    <form action="" class="mt-3" @submit.stop.prevent="submit()">
                        <div class="mb-3">
                            <label for="show-encoded-message" class="form-label">Message</label>
                            <input type="text" id="show-encoded-message" class="form-control" x-model="encoded">
                        </div>
                        <div class="mb-3">
                            <label for="show-key" class="form-label">Key</label>
                            <input type="text" id="show-key" class="form-control" x-model="key">
                        </div>
                        <button type="submit" class="btn btn-primary">Show</button>
                    </form>

                    <template x-if="error != null">
                        <div id="show-error">
                            <hr>
                            <div class="alert alert-danger" x-text="error"></div>
                        </div>
                    </template>

                    <template x-if="result != null && error == null">
                        <div id="show-result">
                            <hr>
                            <ul class="list-group">
                                <li class="list-group-item d-flex justify-content-between align-items-center gap-2">
                                    <div class="row flex-grow-1">
                                        <div class="col-12 col-md-2 fw-bold">Original:</div>
                                        <div class="col" x-text="result.original"></div>
                                    </div>
                                    <button class="btn btn-link" @click.prevent="clip(result.original)">
                                        <i class="fas fa-copy"></i>
                                    </button>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center gap-2">
                                    <div class="row flex-grow-1">
                                        <div class="col-12 col-md-2 fw-bold">Decoded:</div>
                                        <div class="col" x-text="result.decoded"></div>
                                    </div>
                                    <button class="btn btn-link" @click.prevent="clip(result.decoded)">
                                        <i class="fas fa-copy"></i>
                                    </button>
                                </li>
                            </ul>
                        </div>
                    </template>
                </div>
            </div>
        </div>
    </div>

    <h5 class="my-3">Chat Application</h5>
    <div class="card shadow-sm">
        <iframe src="{% url 'chat:room' room_name='lobby' %}?focus=false" title="Secure Chat Application"
                class="border-0"
                height="500px"></iframe>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'plugins/seedrandom.min.js' %}"></script>
    <script src="{% static 'chat/cipher.js' %}"></script>
    <script src="{% static 'chat/logic.js' %}"></script>
    <script src="{% static 'plugins/alpine.min.js' %}" defer></script>
{% endblock %}}